-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.nodes
(
    id bigint NOT NULL,
    version integer NOT NULL,
    user_id integer NOT NULL,
    tstamp timestamp without time zone NOT NULL,
    changeset_id bigint NOT NULL,
    tags hstore,
    geom geometry,
    CONSTRAINT pk_nodes PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.relation_members
(
    relation_id bigint NOT NULL,
    member_id bigint NOT NULL,
    member_type character(1) COLLATE pg_catalog."default" NOT NULL,
    member_role text COLLATE pg_catalog."default" NOT NULL,
    sequence_id integer NOT NULL,
    CONSTRAINT pk_relation_members PRIMARY KEY (relation_id, sequence_id)
);

ALTER TABLE IF EXISTS public.relation_members
    ALTER COLUMN relation_id
    SET (n_distinct=-0.09);

ALTER TABLE IF EXISTS public.relation_members
    ALTER COLUMN member_id
    SET (n_distinct=-0.62);

ALTER TABLE IF EXISTS public.relation_members
    ALTER COLUMN member_role
    SET (n_distinct=6500);

ALTER TABLE IF EXISTS public.relation_members
    ALTER COLUMN sequence_id
    SET (n_distinct=10000);

CREATE TABLE IF NOT EXISTS public.relations
(
    id bigint NOT NULL,
    version integer NOT NULL,
    user_id integer NOT NULL,
    tstamp timestamp without time zone NOT NULL,
    changeset_id bigint NOT NULL,
    tags hstore,
    CONSTRAINT pk_relations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.schema_info
(
    version integer NOT NULL,
    CONSTRAINT pk_schema_info PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.way_nodes
(
    way_id bigint NOT NULL,
    node_id bigint NOT NULL,
    sequence_id integer NOT NULL,
    CONSTRAINT pk_way_nodes PRIMARY KEY (way_id, sequence_id)
);

ALTER TABLE IF EXISTS public.way_nodes
    ALTER COLUMN way_id
    SET (n_distinct=-0.08);

ALTER TABLE IF EXISTS public.way_nodes
    ALTER COLUMN node_id
    SET (n_distinct=-0.83);

ALTER TABLE IF EXISTS public.way_nodes
    ALTER COLUMN sequence_id
    SET (n_distinct=2000);

CREATE TABLE IF NOT EXISTS public.ways
(
    id bigint NOT NULL,
    version integer NOT NULL,
    user_id integer NOT NULL,
    tstamp timestamp without time zone NOT NULL,
    changeset_id bigint NOT NULL,
    tags hstore,
    nodes bigint[],
    linestring geometry,
    CONSTRAINT pk_ways PRIMARY KEY (id)
);
END;